### ISSUE TITLE
Layouts using Float

### ISSUE THREAD

**Issue by stanl3y** [incompl/csslayoutsite#144]
Is it true that floats are no longer the no. 1 recommendation for website layouts? 
If so, it might be worth mentioning in the relevant section.

Thanks for a great tutorial!

**Comment by incompl** [comment]
On this site I try not to give specific recommendations, but instead explain how everything works, because they are all used in the wild. Is there anything on the site that suggests one method is "better" or "more recommended"? If so, I'd want to remove that.

**Comment by stanl3y** [comment]
As a newcomer, I would find those helpful.. but fair enough. 

Elsewhere on the site? Not that I can think of.

**Comment by incompl** [comment]
I absolutely understand why you're looking for specific recommendations. It would be simpler if you could simply learn the important stuff. In practice, I don't know what is most important to you because I don't know what kind of project you're working on. My experience has been that no one solution is perfect and that there is no replacement for fundamentally understanding the different tools at your disposal. That is why teaching that foundational knowledge is the goal for this site. There are many, many sites that preach specific techniques: I believe this site has been successful because it explains how CSS works in a way that is applicable no matter what project you're working on or what methodologies you prescribe to.

**Comment by stanl3y** [comment]
OK, that does make sense.. especially since you get to focus on the essentials.. which are (more-less) objective and non-disputable. 
And as a concise overview of what is available, the site was extremely useful. Thank you!
